[package]
name    = "world"
version = "0.1.0"
edition = "2021"

[lib]
name = "world"
path = "../../src_world/lib.rs"

[dependencies]
nalgebra = "0.31.0"
bevy_ecs = "0.7.0"
bevy = "0.7.0"
bevy_egui = "0.14.0"