[package]
name    = "examples"
version = "0.1.0"
edition = "2021"
default-run = "robot"

[dependencies]
bevy = "0.7.0"
bevy_obj = "0.7.0"
obj-rs = { version =  "0.7.0", default-features = false }

[[bin]]
name = "robot"
path = "./robot.rs"